const reviews = [
  {
    reviewer: "tinyTykesFan",
    rating: 4,
    comment: "It’s okay. Nothing too exciting, but it works.",
    date: "2025-03-17",
  },
  {
    reviewer: "noisyNeighbor",
    rating: 2,
    comment: "Beautifully designed and safe for all ages.",
    date: "2025-01-01",
  },
  {
    reviewer: "playroomQueen",
    rating: 3,
    comment: "My dog thinks it’s his now. 10/10 would confuse everyone again.",
    date: "2025-03-30",
  },
  {
    reviewer: "softToyLover",
    rating: 5,
    comment: "Very educational and engaging. Worth every penny.",
    date: "2024-12-01",
  },
  {
    reviewer: "grannySmith",
    rating: 5,
    comment: "Perfect gift for birthdays or holidays. Highly recommend!",
    date: "2025-04-24",
  },
  {
    reviewer: "blockBuilder77",
    rating: 3,
    comment: "Average toy. My kid plays with it sometimes.",
    date: "2025-03-28",
  },
  {
    reviewer: "coolCousin123",
    rating: 4,
    comment: "Kept my child quiet for 30 minutes. That’s basically magic.",
    date: "2025-05-02",
  },
  {
    reviewer: "funAuntLilly",
    rating: 5,
    comment: "My child hasn’t stopped playing with it since we got it!",
    date: "2025-04-06",
  },
  {
    reviewer: "momOfTwins",
    rating: 4,
    comment:
      "Great toy! I’ve stepped on it five times this week—still love it!",
    date: "2025-05-16",
  },
  {
    reviewer: "grandpaRick",
    rating: 3,
    comment: "Decent quality for the price.",
    date: "2024-12-05",
  },
  {
    reviewer: "quietReader",
    rating: 3,
    comment: "Not bad, but not amazing either.",
    date: "2025-01-28",
  },
  {
    reviewer: "kiddoMom7",
    rating: 5,
    comment: "Beautifully designed and safe for all ages.",
    date: "2025-06-07",
  },
  {
    reviewer: "actionToyFan",
    rating: 3,
    comment: "Not bad, but not amazing either.",
    date: "2025-02-11",
  },
  {
    reviewer: "singleDadMike",
    rating: 4,
    comment: "My kid tried to eat it, but hey, at least it's non-toxic!",
    date: "2025-02-27",
  },
  {
    reviewer: "babysitterJane",
    rating: 4,
    comment: "Arrived on time and works perfectly!",
    date: "2025-03-20",
  },
  {
    reviewer: "teacherKay",
    rating: 5,
    comment: "Perfect for my classroom. Makes learning fun and interactive!",
    date: "2025-01-14",
  },
  {
    reviewer: "johnnyBravo",
    rating: 4,
    comment: "Fun and engaging toy, keeps kids busy for hours.",
    date: "2025-04-15",
  },
  {
    reviewer: "uncleJoe",
    rating: 5,
    comment: "Perfect gift for birthdays or holidays. Highly recommend!",
    date: "2024-12-07",
  },
  {
    reviewer: "playroomKing",
    rating: 4,
    comment: "My kids can't get enough of this toy!",
    date: "2025-05-22",
  },
  {
    reviewer: "toyCollector",
    rating: 5,
    comment: "Well-made and durable. Highly recommend.",
    date: "2025-06-01",
  },
  {
    reviewer: "creativeMom",
    rating: 4,
    comment: "Stimulates creativity and imagination. Love it!",
    date: "2025-03-05",
  },
  {
    reviewer: "grandmaJoy",
    rating: 5,
    comment: "Soft and cuddly! My granddaughter sleeps with it every night.",
    date: "2024-12-19",
  },
  {
    reviewer: "dadOf3",
    rating: 4,
    comment: "Good quality and safe for kids. Worth the price.",
    date: "2025-05-07",
  },
  {
    reviewer: "mommyB",
    rating: 4,
    comment: "Easy to clean and very colorful, my kids love it.",
    date: "2025-04-28",
  },
  {
    reviewer: "littleExplorer",
    rating: 5,
    comment: "Helps kids learn while having fun. Excellent toy!",
    date: "2025-03-15",
  },
  {
    reviewer: "playdatePro",
    rating: 5,
    comment: "Everyone wants to play with this at our playdates.",
    date: "2025-05-11",
  },
  {
    reviewer: "funDad",
    rating: 4,
    comment: "Brings back my childhood memories while playing with my kids.",
    date: "2025-02-18",
  },
  {
    reviewer: "busyMom",
    rating: 5,
    comment: "Keeps my kids occupied so I can get some work done.",
    date: "2025-03-23",
  },
  {
    reviewer: "toyTester",
    rating: 4,
    comment: "Great toy, perfect for indoor and outdoor play.",
    date: "2025-04-10",
  },
  {
    reviewer: "grandpaTom",
    rating: 5,
    comment: "Bought this for my grandkids, they love it!",
    date: "2024-12-23",
  },
  {
    reviewer: "happyAunt",
    rating: 4,
    comment: "A hit with all the kids in the family.",
    date: "2025-01-30",
  },
  {
    reviewer: "funUncle",
    rating: 4,
    comment: "Makes playtime more exciting and fun.",
    date: "2025-03-08",
  },
  {
    reviewer: "toddlerMom",
    rating: 5,
    comment: "Safe for toddlers and very engaging.",
    date: "2025-02-07",
  },
  {
    reviewer: "toyEnthusiast",
    rating: 4,
    comment: "Quality materials and fun design.",
    date: "2025-05-15",
  },
  {
    reviewer: "momOnTheGo",
    rating: 4,
    comment: "Compact and easy to carry around.",
    date: "2025-04-12",
  },
  {
    reviewer: "creativeDad",
    rating: 5,
    comment: "Helps develop fine motor skills. Fantastic!",
    date: "2025-03-03",
  },
  {
    reviewer: "playgroundMom",
    rating: 4,
    comment: "Good for social play with other kids.",
    date: "2025-04-18",
  },
  {
    reviewer: "craftyMom",
    rating: 5,
    comment: "Stimulates creativity and imagination.",
    date: "2025-01-25",
  },
  {
    reviewer: "firstTimeBuyer",
    rating: 5,
    comment: "Exceeded my expectations. Very happy with this purchase.",
    date: "2025-05-05",
  },
  {
    reviewer: "momOfTwins",
    rating: 4,
    comment: "Great for twins to play together without fights.",
    date: "2025-06-03",
  },
  {
    reviewer: "toyMom",
    rating: 5,
    comment: "Durable and educational. Love it!",
    date: "2025-02-20",
  },
  {
    reviewer: "dadAndSon",
    rating: 4,
    comment: "Perfect bonding toy for father and son.",
    date: "2025-03-26",
  },
  {
    reviewer: "teacherSue",
    rating: 5,
    comment: "Excellent educational tool in the classroom.",
    date: "2025-04-22",
  },
  {
    reviewer: "parentingGuru",
    rating: 5,
    comment: "Safe, fun, and educational all in one.",
    date: "2025-06-09",
  },
  {
    reviewer: "toyReviewer",
    rating: 4,
    comment: "A fun toy that stands out from the rest.",
    date: "2025-02-14",
  },
  {
    reviewer: "momLovesIt",
    rating: 5,
    comment: "My kids can't get enough of this!",
    date: "2025-04-05",
  },
];
